dist: trusty
sudo: required
language: c
cache: ccache
compiler:
  - gcc

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libxen-dev -y
  - sudo apt-get install --only-upgrade binutils gcc -y

env:
  - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS=
  - PLATFORM=hw MACHINE=i486 ELF=elf TESTS=qemu EXTRAFLAGS='-- -F ACLFLAGS=-m32 -F ACLFLAGS=-march=i686'
  - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS= CXX='false'
  - PLATFORM=hw MACHINE=x86_64 TESTS=none KERNONLY=-k EXTRAFLAGS= 

script:
  - git submodule update --init
  - ./build-rr.sh -o myobj -j16 -qq ${KERNONLY} ${PLATFORM} ${EXTRAFLAGS}
  - . ./myobj/config
  - ./tests/buildtests.sh ${KERNONLY}
  - ./tests/runtests.sh ${TESTS}


# touch me to force a travis rebuild
